// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    id,
    user_id,
    device_label,
    x25519_public,
    ed25519_public,
    created_at,
    last_seen
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
)
RETURNING id, user_id, device_label, x25519_public, ed25519_public, revoked_at, created_at, last_seen
`

type CreateDeviceParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        int32       `json:"user_id"`
	DeviceLabel   pgtype.Text `json:"device_label"`
	X25519Public  []byte      `json:"x25519_public"`
	Ed25519Public []byte      `json:"ed25519_public"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.DeviceLabel,
		arg.X25519Public,
		arg.Ed25519Public,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceLabel,
		&i.X25519Public,
		&i.Ed25519Public,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getAllDevicesByUserID = `-- name: GetAllDevicesByUserID :many
SELECT id, user_id, device_label, x25519_public, ed25519_public, revoked_at, created_at, last_seen FROM devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllDevicesByUserID(ctx context.Context, userID int32) ([]Device, error) {
	rows, err := q.db.Query(ctx, getAllDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceLabel,
			&i.X25519Public,
			&i.Ed25519Public,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, device_label, x25519_public, ed25519_public, revoked_at, created_at, last_seen FROM devices
WHERE id = $1 AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceLabel,
		&i.X25519Public,
		&i.Ed25519Public,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getDevicePublicKeys = `-- name: GetDevicePublicKeys :one
SELECT x25519_public, ed25519_public
FROM devices
WHERE id = $1 AND revoked_at IS NULL
LIMIT 1
`

type GetDevicePublicKeysRow struct {
	X25519Public  []byte `json:"x25519_public"`
	Ed25519Public []byte `json:"ed25519_public"`
}

func (q *Queries) GetDevicePublicKeys(ctx context.Context, id pgtype.UUID) (GetDevicePublicKeysRow, error) {
	row := q.db.QueryRow(ctx, getDevicePublicKeys, id)
	var i GetDevicePublicKeysRow
	err := row.Scan(&i.X25519Public, &i.Ed25519Public)
	return i, err
}

const getDevicesByUserID = `-- name: GetDevicesByUserID :many
SELECT id, user_id, device_label, x25519_public, ed25519_public, revoked_at, created_at, last_seen FROM devices
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetDevicesByUserID(ctx context.Context, userID int32) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceLabel,
			&i.X25519Public,
			&i.Ed25519Public,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDevicePublicKeys = `-- name: GetUserDevicePublicKeys :many
SELECT id, device_label, x25519_public, ed25519_public, created_at
FROM devices
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type GetUserDevicePublicKeysRow struct {
	ID            pgtype.UUID      `json:"id"`
	DeviceLabel   pgtype.Text      `json:"device_label"`
	X25519Public  []byte           `json:"x25519_public"`
	Ed25519Public []byte           `json:"ed25519_public"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserDevicePublicKeys(ctx context.Context, userID int32) ([]GetUserDevicePublicKeysRow, error) {
	rows, err := q.db.Query(ctx, getUserDevicePublicKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserDevicePublicKeysRow{}
	for rows.Next() {
		var i GetUserDevicePublicKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceLabel,
			&i.X25519Public,
			&i.Ed25519Public,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE devices
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeDevice, id)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices
SET last_seen = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, id)
	return err
}
