// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ID          int32            `json:"id"`
	PageID      int32            `json:"page_id"`
	UserID      int32            `json:"user_id"`
	BlockOrder  pgtype.Int4      `json:"block_order"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Title       pgtype.Text      `json:"title"`
	Description pgtype.Text      `json:"description"`
	Layout      string           `json:"layout"`
	BlockType   pgtype.Text      `json:"block_type"`
	Variant     pgtype.Text      `json:"variant"`
	Properties  []byte           `json:"properties"`
}

type Page struct {
	ID          int32            `json:"id"`
	UserID      int32            `json:"user_id"`
	Name        pgtype.Text      `json:"name"`
	Handle      string           `json:"handle"`
	BannerImage pgtype.Text      `json:"banner_image"`
	Image       pgtype.Text      `json:"image"`
	Bio         pgtype.Text      `json:"bio"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Preference struct {
	ID                  int32            `json:"id"`
	PageID              int32            `json:"page_id"`
	UserID              int32            `json:"user_id"`
	SocialIconsPosition string           `json:"social_icons_position"`
	HideShop            bool             `json:"hide_shop"`
	HideLinkBranding    bool             `json:"hide_link_branding"`
	HideShareButton     bool             `json:"hide_share_button"`
	ShopLayout          string           `json:"shop_layout"`
	ButtonStyle         string           `json:"button_style"`
	Theme               pgtype.Text      `json:"theme"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID           int32            `json:"id"`
	UserID       int32            `json:"user_id"`
	SessionToken string           `json:"session_token"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	ActivePageID pgtype.Int4      `json:"active_page_id"`
}

type User struct {
	ID            int32            `json:"id"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	PasswordHash  string           `json:"password_hash"`
	EmailVerified bool             `json:"email_verified"`
	Image         string           `json:"image"`
}
