// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkHandleExists = `-- name: CheckHandleExists :one
SELECT EXISTS(
    SELECT 1 FROM pages
    WHERE handle = $1 AND id != COALESCE($2, 0)
)
`

type CheckHandleExistsParams struct {
	Handle string `json:"handle"`
	ID     int32  `json:"id"`
}

func (q *Queries) CheckHandleExists(ctx context.Context, arg CheckHandleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkHandleExists, arg.Handle, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUserPages = `-- name: CountUserPages :one
SELECT COUNT(*) FROM pages
WHERE user_id = $1
`

func (q *Queries) CountUserPages(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPages, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (
    user_id,
    name,
    handle,
    banner_image,
    image,
    bio,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, handle, banner_image, image, bio, is_active, created_at, updated_at
`

type CreatePageParams struct {
	UserID      int32       `json:"user_id"`
	Name        pgtype.Text `json:"name"`
	Handle      string      `json:"handle"`
	BannerImage pgtype.Text `json:"banner_image"`
	Image       pgtype.Text `json:"image"`
	Bio         pgtype.Text `json:"bio"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.UserID,
		arg.Name,
		arg.Handle,
		arg.BannerImage,
		arg.Image,
		arg.Bio,
		arg.IsActive,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Handle,
		&i.BannerImage,
		&i.Image,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages
WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getActivePagesByUserID = `-- name: GetActivePagesByUserID :many
SELECT id, user_id, name, handle, banner_image, image, bio, is_active, created_at, updated_at FROM pages
WHERE user_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) GetActivePagesByUserID(ctx context.Context, userID int32) ([]Page, error) {
	rows, err := q.db.Query(ctx, getActivePagesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Handle,
			&i.BannerImage,
			&i.Image,
			&i.Bio,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPages = `-- name: GetAllPages :many
SELECT id, user_id, name, handle, banner_image, image, bio, is_active, created_at, updated_at FROM pages
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllPagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllPages(ctx context.Context, arg GetAllPagesParams) ([]Page, error) {
	rows, err := q.db.Query(ctx, getAllPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Handle,
			&i.BannerImage,
			&i.Image,
			&i.Bio,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageByHandle = `-- name: GetPageByHandle :one
SELECT id, user_id, name, handle, banner_image, image, bio, is_active, created_at, updated_at FROM pages
WHERE handle = $1
`

func (q *Queries) GetPageByHandle(ctx context.Context, handle string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByHandle, handle)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Handle,
		&i.BannerImage,
		&i.Image,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, user_id, name, handle, banner_image, image, bio, is_active, created_at, updated_at FROM pages
WHERE id = $1
`

func (q *Queries) GetPageByID(ctx context.Context, id int32) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Handle,
		&i.BannerImage,
		&i.Image,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPagesByUserID = `-- name: GetPagesByUserID :many
SELECT id, user_id, name, handle, banner_image, image, bio, is_active, created_at, updated_at FROM pages
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPagesByUserID(ctx context.Context, userID int32) ([]Page, error) {
	rows, err := q.db.Query(ctx, getPagesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Handle,
			&i.BannerImage,
			&i.Image,
			&i.Bio,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET
    name = COALESCE($1, name),
    handle = COALESCE($2, handle),
    banner_image = COALESCE($3, banner_image),
    image = COALESCE($4, image),
    bio = COALESCE($5, bio),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $7
RETURNING id, user_id, name, handle, banner_image, image, bio, is_active, created_at, updated_at
`

type UpdatePageParams struct {
	Name        pgtype.Text `json:"name"`
	Handle      pgtype.Text `json:"handle"`
	BannerImage pgtype.Text `json:"banner_image"`
	Image       pgtype.Text `json:"image"`
	Bio         pgtype.Text `json:"bio"`
	IsActive    pgtype.Bool `json:"is_active"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.Name,
		arg.Handle,
		arg.BannerImage,
		arg.Image,
		arg.Bio,
		arg.IsActive,
		arg.ID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Handle,
		&i.BannerImage,
		&i.Image,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
