// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPreferences = `-- name: CreatePreferences :one
INSERT INTO preferences (
    page_id,
    user_id,
    social_icons_position,
    hide_shop,
    hide_link_branding,
    hide_share_button,
    shop_layout,
    button_style,
    theme
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, page_id, user_id, social_icons_position, hide_shop, hide_link_branding, hide_share_button, shop_layout, button_style, theme, created_at, updated_at
`

type CreatePreferencesParams struct {
	PageID              int32       `json:"page_id"`
	UserID              int32       `json:"user_id"`
	SocialIconsPosition string      `json:"social_icons_position"`
	HideShop            bool        `json:"hide_shop"`
	HideLinkBranding    bool        `json:"hide_link_branding"`
	HideShareButton     bool        `json:"hide_share_button"`
	ShopLayout          string      `json:"shop_layout"`
	ButtonStyle         string      `json:"button_style"`
	Theme               pgtype.Text `json:"theme"`
}

func (q *Queries) CreatePreferences(ctx context.Context, arg CreatePreferencesParams) (Preference, error) {
	row := q.db.QueryRow(ctx, createPreferences,
		arg.PageID,
		arg.UserID,
		arg.SocialIconsPosition,
		arg.HideShop,
		arg.HideLinkBranding,
		arg.HideShareButton,
		arg.ShopLayout,
		arg.ButtonStyle,
		arg.Theme,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.UserID,
		&i.SocialIconsPosition,
		&i.HideShop,
		&i.HideLinkBranding,
		&i.HideShareButton,
		&i.ShopLayout,
		&i.ButtonStyle,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePreferences = `-- name: DeletePreferences :exec
DELETE FROM preferences
WHERE id = $1
`

func (q *Queries) DeletePreferences(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePreferences, id)
	return err
}

const deletePreferencesByPageID = `-- name: DeletePreferencesByPageID :exec
DELETE FROM preferences
WHERE page_id = $1
`

func (q *Queries) DeletePreferencesByPageID(ctx context.Context, pageID int32) error {
	_, err := q.db.Exec(ctx, deletePreferencesByPageID, pageID)
	return err
}

const getPreferencesByID = `-- name: GetPreferencesByID :one
SELECT id, page_id, user_id, social_icons_position, hide_shop, hide_link_branding, hide_share_button, shop_layout, button_style, theme, created_at, updated_at FROM preferences
WHERE id = $1
`

func (q *Queries) GetPreferencesByID(ctx context.Context, id int32) (Preference, error) {
	row := q.db.QueryRow(ctx, getPreferencesByID, id)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.UserID,
		&i.SocialIconsPosition,
		&i.HideShop,
		&i.HideLinkBranding,
		&i.HideShareButton,
		&i.ShopLayout,
		&i.ButtonStyle,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreferencesByPageID = `-- name: GetPreferencesByPageID :one
SELECT id, page_id, user_id, social_icons_position, hide_shop, hide_link_branding, hide_share_button, shop_layout, button_style, theme, created_at, updated_at FROM preferences
WHERE page_id = $1
`

func (q *Queries) GetPreferencesByPageID(ctx context.Context, pageID int32) (Preference, error) {
	row := q.db.QueryRow(ctx, getPreferencesByPageID, pageID)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.UserID,
		&i.SocialIconsPosition,
		&i.HideShop,
		&i.HideLinkBranding,
		&i.HideShareButton,
		&i.ShopLayout,
		&i.ButtonStyle,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreferencesByUserID = `-- name: GetPreferencesByUserID :many
SELECT id, page_id, user_id, social_icons_position, hide_shop, hide_link_branding, hide_share_button, shop_layout, button_style, theme, created_at, updated_at FROM preferences
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPreferencesByUserID(ctx context.Context, userID int32) ([]Preference, error) {
	rows, err := q.db.Query(ctx, getPreferencesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preference{}
	for rows.Next() {
		var i Preference
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.UserID,
			&i.SocialIconsPosition,
			&i.HideShop,
			&i.HideLinkBranding,
			&i.HideShareButton,
			&i.ShopLayout,
			&i.ButtonStyle,
			&i.Theme,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE preferences
SET
    social_icons_position = COALESCE($1, social_icons_position),
    hide_shop = COALESCE($2, hide_shop),
    hide_link_branding = COALESCE($3, hide_link_branding),
    hide_share_button = COALESCE($4, hide_share_button),
    shop_layout = COALESCE($5, shop_layout),
    button_style = COALESCE($6, button_style),
    theme = COALESCE($7, theme),
    updated_at = NOW()
WHERE id = $8
RETURNING id, page_id, user_id, social_icons_position, hide_shop, hide_link_branding, hide_share_button, shop_layout, button_style, theme, created_at, updated_at
`

type UpdatePreferencesParams struct {
	SocialIconsPosition pgtype.Text `json:"social_icons_position"`
	HideShop            pgtype.Bool `json:"hide_shop"`
	HideLinkBranding    pgtype.Bool `json:"hide_link_branding"`
	HideShareButton     pgtype.Bool `json:"hide_share_button"`
	ShopLayout          pgtype.Text `json:"shop_layout"`
	ButtonStyle         pgtype.Text `json:"button_style"`
	Theme               pgtype.Text `json:"theme"`
	ID                  int32       `json:"id"`
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (Preference, error) {
	row := q.db.QueryRow(ctx, updatePreferences,
		arg.SocialIconsPosition,
		arg.HideShop,
		arg.HideLinkBranding,
		arg.HideShareButton,
		arg.ShopLayout,
		arg.ButtonStyle,
		arg.Theme,
		arg.ID,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.UserID,
		&i.SocialIconsPosition,
		&i.HideShop,
		&i.HideLinkBranding,
		&i.HideShareButton,
		&i.ShopLayout,
		&i.ButtonStyle,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePreferencesByPageID = `-- name: UpdatePreferencesByPageID :one
UPDATE preferences
SET
    social_icons_position = COALESCE($1, social_icons_position),
    hide_shop = COALESCE($2, hide_shop),
    hide_link_branding = COALESCE($3, hide_link_branding),
    hide_share_button = COALESCE($4, hide_share_button),
    shop_layout = COALESCE($5, shop_layout),
    button_style = COALESCE($6, button_style),
    theme = COALESCE($7, theme),
    updated_at = NOW()
WHERE page_id = $8
RETURNING id, page_id, user_id, social_icons_position, hide_shop, hide_link_branding, hide_share_button, shop_layout, button_style, theme, created_at, updated_at
`

type UpdatePreferencesByPageIDParams struct {
	SocialIconsPosition pgtype.Text `json:"social_icons_position"`
	HideShop            pgtype.Bool `json:"hide_shop"`
	HideLinkBranding    pgtype.Bool `json:"hide_link_branding"`
	HideShareButton     pgtype.Bool `json:"hide_share_button"`
	ShopLayout          pgtype.Text `json:"shop_layout"`
	ButtonStyle         pgtype.Text `json:"button_style"`
	Theme               pgtype.Text `json:"theme"`
	PageID              int32       `json:"page_id"`
}

func (q *Queries) UpdatePreferencesByPageID(ctx context.Context, arg UpdatePreferencesByPageIDParams) (Preference, error) {
	row := q.db.QueryRow(ctx, updatePreferencesByPageID,
		arg.SocialIconsPosition,
		arg.HideShop,
		arg.HideLinkBranding,
		arg.HideShareButton,
		arg.ShopLayout,
		arg.ButtonStyle,
		arg.Theme,
		arg.PageID,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.UserID,
		&i.SocialIconsPosition,
		&i.HideShop,
		&i.HideLinkBranding,
		&i.HideShareButton,
		&i.ShopLayout,
		&i.ButtonStyle,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPreferences = `-- name: UpsertPreferences :one
INSERT INTO preferences (
    page_id,
    user_id,
    social_icons_position,
    hide_shop,
    hide_link_branding,
    hide_share_button,
    shop_layout,
    button_style,
    theme
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (page_id) DO UPDATE SET
    social_icons_position = EXCLUDED.social_icons_position,
    hide_shop = EXCLUDED.hide_shop,
    hide_link_branding = EXCLUDED.hide_link_branding,
    hide_share_button = EXCLUDED.hide_share_button,
    shop_layout = EXCLUDED.shop_layout,
    button_style = EXCLUDED.button_style,
    theme = EXCLUDED.theme,
    updated_at = NOW()
RETURNING id, page_id, user_id, social_icons_position, hide_shop, hide_link_branding, hide_share_button, shop_layout, button_style, theme, created_at, updated_at
`

type UpsertPreferencesParams struct {
	PageID              int32       `json:"page_id"`
	UserID              int32       `json:"user_id"`
	SocialIconsPosition string      `json:"social_icons_position"`
	HideShop            bool        `json:"hide_shop"`
	HideLinkBranding    bool        `json:"hide_link_branding"`
	HideShareButton     bool        `json:"hide_share_button"`
	ShopLayout          string      `json:"shop_layout"`
	ButtonStyle         string      `json:"button_style"`
	Theme               pgtype.Text `json:"theme"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (Preference, error) {
	row := q.db.QueryRow(ctx, upsertPreferences,
		arg.PageID,
		arg.UserID,
		arg.SocialIconsPosition,
		arg.HideShop,
		arg.HideLinkBranding,
		arg.HideShareButton,
		arg.ShopLayout,
		arg.ButtonStyle,
		arg.Theme,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.UserID,
		&i.SocialIconsPosition,
		&i.HideShop,
		&i.HideLinkBranding,
		&i.HideShareButton,
		&i.ShopLayout,
		&i.ButtonStyle,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
