// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CheckHandleExists(ctx context.Context, arg CheckHandleExistsParams) (bool, error)
	CountActiveBlocksByPageID(ctx context.Context, pageID int32) (int64, error)
	CountBlocksByPageID(ctx context.Context, pageID int32) (int64, error)
	CountUserPages(ctx context.Context, userID int32) (int64, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreatePreferences(ctx context.Context, arg CreatePreferencesParams) (Preference, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteBlock(ctx context.Context, id int32) error
	DeleteBlocksByPageID(ctx context.Context, pageID int32) error
	DeleteExpiredSessions(ctx context.Context) error
	DeletePage(ctx context.Context, id int32) error
	DeletePreferences(ctx context.Context, id int32) error
	DeletePreferencesByPageID(ctx context.Context, pageID int32) error
	DeleteSession(ctx context.Context, id int32) error
	DeleteUserSessions(ctx context.Context, userID int32) error
	GetActiveBlocksByPageID(ctx context.Context, pageID int32) ([]Block, error)
	GetActivePagesByUserID(ctx context.Context, userID int32) ([]Page, error)
	GetAllPages(ctx context.Context, arg GetAllPagesParams) ([]Page, error)
	GetBlockByID(ctx context.Context, id int32) (Block, error)
	GetBlocksByPageID(ctx context.Context, pageID int32) ([]Block, error)
	GetBlocksByPageIDAndType(ctx context.Context, arg GetBlocksByPageIDAndTypeParams) ([]Block, error)
	GetBlocksByUserID(ctx context.Context, userID int32) ([]Block, error)
	GetPageByHandle(ctx context.Context, handle string) (Page, error)
	GetPageByID(ctx context.Context, id int32) (Page, error)
	GetPagesByUserID(ctx context.Context, userID int32) ([]Page, error)
	GetPreferencesByID(ctx context.Context, id int32) (Preference, error)
	GetPreferencesByPageID(ctx context.Context, pageID int32) (Preference, error)
	GetPreferencesByUserID(ctx context.Context, userID int32) ([]Preference, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID int32) ([]Session, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetUserMostRecentPage(ctx context.Context, userID int32) (Page, error)
	ReorderBlocks(ctx context.Context, arg ReorderBlocksParams) error
	UpdateBlock(ctx context.Context, arg UpdateBlockParams) (Block, error)
	UpdateBlockOrder(ctx context.Context, arg UpdateBlockOrderParams) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (Preference, error)
	UpdatePreferencesByPageID(ctx context.Context, arg UpdatePreferencesByPageIDParams) (Preference, error)
	UpdateSessionWithActivePage(ctx context.Context, arg UpdateSessionWithActivePageParams) (Session, error)
	UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error
	UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (Preference, error)
}

var _ Querier = (*Queries)(nil)
