// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, email_verified, image)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, email_verified, image, created_at, updated_at
`

type CreateUserParams struct {
	Username      string `json:"username"`
	Email         string `json:"email"`
	PasswordHash  string `json:"password_hash"`
	EmailVerified bool   `json:"email_verified"`
	Image         string `json:"image"`
}

type CreateUserRow struct {
	ID            int32            `json:"id"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"email_verified"`
	Image         string           `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.Image,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, email_verified, image, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            int32            `json:"id"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	PasswordHash  string           `json:"password_hash"`
	EmailVerified bool             `json:"email_verified"`
	Image         string           `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, email_verified, image, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            int32            `json:"id"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"email_verified"`
	Image         string           `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users
SET email_verified = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserEmailVerifiedParams struct {
	ID            int32 `json:"id"`
	EmailVerified bool  `json:"email_verified"`
}

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, arg.ID, arg.EmailVerified)
	return err
}
