// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_login_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLoginAttachment = `-- name: AddLoginAttachment :one
INSERT INTO vault_login_attachments (
    login_item_id,
    filename,
    file_path,
    file_size,
    mime_type
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, login_item_id, filename, file_path, file_size, mime_type, created_at
`

type AddLoginAttachmentParams struct {
	LoginItemID int32       `json:"login_item_id"`
	Filename    string      `json:"filename"`
	FilePath    string      `json:"file_path"`
	FileSize    int32       `json:"file_size"`
	MimeType    pgtype.Text `json:"mime_type"`
}

// Login Attachments queries
func (q *Queries) AddLoginAttachment(ctx context.Context, arg AddLoginAttachmentParams) (VaultLoginAttachment, error) {
	row := q.db.QueryRow(ctx, addLoginAttachment,
		arg.LoginItemID,
		arg.Filename,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
	)
	var i VaultLoginAttachment
	err := row.Scan(
		&i.ID,
		&i.LoginItemID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const addLoginWebsite = `-- name: AddLoginWebsite :one
INSERT INTO vault_login_websites (
    login_item_id,
    url
) VALUES (
    $1, $2
) RETURNING id, login_item_id, url, created_at
`

type AddLoginWebsiteParams struct {
	LoginItemID int32  `json:"login_item_id"`
	Url         string `json:"url"`
}

// Login Websites queries
func (q *Queries) AddLoginWebsite(ctx context.Context, arg AddLoginWebsiteParams) (VaultLoginWebsite, error) {
	row := q.db.QueryRow(ctx, addLoginWebsite, arg.LoginItemID, arg.Url)
	var i VaultLoginWebsite
	err := row.Scan(
		&i.ID,
		&i.LoginItemID,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const createLoginItem = `-- name: CreateLoginItem :one
INSERT INTO vault_login_items (
    vault_id,
    user_id,
    title,
    username,
    password_encrypted,
    totp_secret_encrypted,
    note,
    is_favorite
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, vault_id, user_id, title, username, password_encrypted, totp_secret_encrypted, note, is_favorite, created_at, updated_at, last_used_at
`

type CreateLoginItemParams struct {
	VaultID             int32       `json:"vault_id"`
	UserID              int32       `json:"user_id"`
	Title               string      `json:"title"`
	Username            pgtype.Text `json:"username"`
	PasswordEncrypted   string      `json:"password_encrypted"`
	TotpSecretEncrypted pgtype.Text `json:"totp_secret_encrypted"`
	Note                pgtype.Text `json:"note"`
	IsFavorite          bool        `json:"is_favorite"`
}

func (q *Queries) CreateLoginItem(ctx context.Context, arg CreateLoginItemParams) (VaultLoginItem, error) {
	row := q.db.QueryRow(ctx, createLoginItem,
		arg.VaultID,
		arg.UserID,
		arg.Title,
		arg.Username,
		arg.PasswordEncrypted,
		arg.TotpSecretEncrypted,
		arg.Note,
		arg.IsFavorite,
	)
	var i VaultLoginItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.Username,
		&i.PasswordEncrypted,
		&i.TotpSecretEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAllLoginAttachments = `-- name: DeleteAllLoginAttachments :exec
DELETE FROM vault_login_attachments
WHERE login_item_id = $1
`

func (q *Queries) DeleteAllLoginAttachments(ctx context.Context, loginItemID int32) error {
	_, err := q.db.Exec(ctx, deleteAllLoginAttachments, loginItemID)
	return err
}

const deleteAllLoginWebsites = `-- name: DeleteAllLoginWebsites :exec
DELETE FROM vault_login_websites
WHERE login_item_id = $1
`

func (q *Queries) DeleteAllLoginWebsites(ctx context.Context, loginItemID int32) error {
	_, err := q.db.Exec(ctx, deleteAllLoginWebsites, loginItemID)
	return err
}

const deleteLoginAttachment = `-- name: DeleteLoginAttachment :exec
DELETE FROM vault_login_attachments
WHERE id = $1 AND login_item_id = $2
`

type DeleteLoginAttachmentParams struct {
	ID          int32 `json:"id"`
	LoginItemID int32 `json:"login_item_id"`
}

func (q *Queries) DeleteLoginAttachment(ctx context.Context, arg DeleteLoginAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteLoginAttachment, arg.ID, arg.LoginItemID)
	return err
}

const deleteLoginItem = `-- name: DeleteLoginItem :exec
DELETE FROM vault_login_items
WHERE id = $1 AND user_id = $2
`

type DeleteLoginItemParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteLoginItem(ctx context.Context, arg DeleteLoginItemParams) error {
	_, err := q.db.Exec(ctx, deleteLoginItem, arg.ID, arg.UserID)
	return err
}

const deleteLoginWebsite = `-- name: DeleteLoginWebsite :exec
DELETE FROM vault_login_websites
WHERE id = $1 AND login_item_id = $2
`

type DeleteLoginWebsiteParams struct {
	ID          int32 `json:"id"`
	LoginItemID int32 `json:"login_item_id"`
}

func (q *Queries) DeleteLoginWebsite(ctx context.Context, arg DeleteLoginWebsiteParams) error {
	_, err := q.db.Exec(ctx, deleteLoginWebsite, arg.ID, arg.LoginItemID)
	return err
}

const getLoginAttachmentByID = `-- name: GetLoginAttachmentByID :one
SELECT id, login_item_id, filename, file_path, file_size, mime_type, created_at FROM vault_login_attachments
WHERE id = $1 AND login_item_id = $2
`

type GetLoginAttachmentByIDParams struct {
	ID          int32 `json:"id"`
	LoginItemID int32 `json:"login_item_id"`
}

func (q *Queries) GetLoginAttachmentByID(ctx context.Context, arg GetLoginAttachmentByIDParams) (VaultLoginAttachment, error) {
	row := q.db.QueryRow(ctx, getLoginAttachmentByID, arg.ID, arg.LoginItemID)
	var i VaultLoginAttachment
	err := row.Scan(
		&i.ID,
		&i.LoginItemID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const getLoginAttachments = `-- name: GetLoginAttachments :many
SELECT id, login_item_id, filename, file_path, file_size, mime_type, created_at FROM vault_login_attachments
WHERE login_item_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetLoginAttachments(ctx context.Context, loginItemID int32) ([]VaultLoginAttachment, error) {
	rows, err := q.db.Query(ctx, getLoginAttachments, loginItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultLoginAttachment{}
	for rows.Next() {
		var i VaultLoginAttachment
		if err := rows.Scan(
			&i.ID,
			&i.LoginItemID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginItemByID = `-- name: GetLoginItemByID :one
SELECT id, vault_id, user_id, title, username, password_encrypted, totp_secret_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_login_items
WHERE id = $1 AND user_id = $2
`

type GetLoginItemByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetLoginItemByID(ctx context.Context, arg GetLoginItemByIDParams) (VaultLoginItem, error) {
	row := q.db.QueryRow(ctx, getLoginItemByID, arg.ID, arg.UserID)
	var i VaultLoginItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.Username,
		&i.PasswordEncrypted,
		&i.TotpSecretEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getLoginWebsites = `-- name: GetLoginWebsites :many
SELECT id, login_item_id, url, created_at FROM vault_login_websites
WHERE login_item_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetLoginWebsites(ctx context.Context, loginItemID int32) ([]VaultLoginWebsite, error) {
	rows, err := q.db.Query(ctx, getLoginWebsites, loginItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultLoginWebsite{}
	for rows.Next() {
		var i VaultLoginWebsite
		if err := rows.Scan(
			&i.ID,
			&i.LoginItemID,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLoginItems = `-- name: GetUserLoginItems :many
SELECT id, vault_id, user_id, title, username, password_encrypted, totp_secret_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_login_items
WHERE user_id = $1
ORDER BY is_favorite DESC, updated_at DESC
`

func (q *Queries) GetUserLoginItems(ctx context.Context, userID int32) ([]VaultLoginItem, error) {
	rows, err := q.db.Query(ctx, getUserLoginItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultLoginItem{}
	for rows.Next() {
		var i VaultLoginItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Title,
			&i.Username,
			&i.PasswordEncrypted,
			&i.TotpSecretEncrypted,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultLoginItems = `-- name: GetVaultLoginItems :many
SELECT id, vault_id, user_id, title, username, password_encrypted, totp_secret_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_login_items
WHERE vault_id = $1 AND user_id = $2
ORDER BY is_favorite DESC, updated_at DESC
`

type GetVaultLoginItemsParams struct {
	VaultID int32 `json:"vault_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) GetVaultLoginItems(ctx context.Context, arg GetVaultLoginItemsParams) ([]VaultLoginItem, error) {
	rows, err := q.db.Query(ctx, getVaultLoginItems, arg.VaultID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultLoginItem{}
	for rows.Next() {
		var i VaultLoginItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Title,
			&i.Username,
			&i.PasswordEncrypted,
			&i.TotpSecretEncrypted,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLoginItems = `-- name: SearchLoginItems :many
SELECT id, vault_id, user_id, title, username, password_encrypted, totp_secret_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_login_items
WHERE user_id = $1 AND (
    title ILIKE '%' || $2 || '%' OR
    username ILIKE '%' || $2 || '%' OR
    note ILIKE '%' || $2 || '%'
)
ORDER BY is_favorite DESC, updated_at DESC
`

type SearchLoginItemsParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchLoginItems(ctx context.Context, arg SearchLoginItemsParams) ([]VaultLoginItem, error) {
	rows, err := q.db.Query(ctx, searchLoginItems, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultLoginItem{}
	for rows.Next() {
		var i VaultLoginItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Title,
			&i.Username,
			&i.PasswordEncrypted,
			&i.TotpSecretEncrypted,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleLoginItemFavorite = `-- name: ToggleLoginItemFavorite :one
UPDATE vault_login_items
SET 
    is_favorite = NOT is_favorite,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, vault_id, user_id, title, username, password_encrypted, totp_secret_encrypted, note, is_favorite, created_at, updated_at, last_used_at
`

type ToggleLoginItemFavoriteParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) ToggleLoginItemFavorite(ctx context.Context, arg ToggleLoginItemFavoriteParams) (VaultLoginItem, error) {
	row := q.db.QueryRow(ctx, toggleLoginItemFavorite, arg.ID, arg.UserID)
	var i VaultLoginItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.Username,
		&i.PasswordEncrypted,
		&i.TotpSecretEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateLoginItem = `-- name: UpdateLoginItem :one
UPDATE vault_login_items
SET 
    title = $2,
    username = $3,
    password_encrypted = $4,
    totp_secret_encrypted = $5,
    note = $6,
    is_favorite = $7,
    updated_at = NOW()
WHERE id = $1 AND user_id = $8
RETURNING id, vault_id, user_id, title, username, password_encrypted, totp_secret_encrypted, note, is_favorite, created_at, updated_at, last_used_at
`

type UpdateLoginItemParams struct {
	ID                  int32       `json:"id"`
	Title               string      `json:"title"`
	Username            pgtype.Text `json:"username"`
	PasswordEncrypted   string      `json:"password_encrypted"`
	TotpSecretEncrypted pgtype.Text `json:"totp_secret_encrypted"`
	Note                pgtype.Text `json:"note"`
	IsFavorite          bool        `json:"is_favorite"`
	UserID              int32       `json:"user_id"`
}

func (q *Queries) UpdateLoginItem(ctx context.Context, arg UpdateLoginItemParams) (VaultLoginItem, error) {
	row := q.db.QueryRow(ctx, updateLoginItem,
		arg.ID,
		arg.Title,
		arg.Username,
		arg.PasswordEncrypted,
		arg.TotpSecretEncrypted,
		arg.Note,
		arg.IsFavorite,
		arg.UserID,
	)
	var i VaultLoginItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.Username,
		&i.PasswordEncrypted,
		&i.TotpSecretEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateLoginItemLastUsed = `-- name: UpdateLoginItemLastUsed :exec
UPDATE vault_login_items
SET last_used_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateLoginItemLastUsedParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) UpdateLoginItemLastUsed(ctx context.Context, arg UpdateLoginItemLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateLoginItemLastUsed, arg.ID, arg.UserID)
	return err
}
