// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_alias_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAliasAttachment = `-- name: AddAliasAttachment :one
INSERT INTO vault_alias_attachments (
    alias_item_id,
    filename,
    file_path,
    file_size,
    mime_type
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, alias_item_id, filename, file_path, file_size, mime_type, created_at
`

type AddAliasAttachmentParams struct {
	AliasItemID int32       `json:"alias_item_id"`
	Filename    string      `json:"filename"`
	FilePath    string      `json:"file_path"`
	FileSize    int32       `json:"file_size"`
	MimeType    pgtype.Text `json:"mime_type"`
}

// Alias Attachments queries
func (q *Queries) AddAliasAttachment(ctx context.Context, arg AddAliasAttachmentParams) (VaultAliasAttachment, error) {
	row := q.db.QueryRow(ctx, addAliasAttachment,
		arg.AliasItemID,
		arg.Filename,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
	)
	var i VaultAliasAttachment
	err := row.Scan(
		&i.ID,
		&i.AliasItemID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const createAliasItem = `-- name: CreateAliasItem :one
INSERT INTO vault_alias_items (
    vault_id,
    user_id,
    title,
    alias_prefix,
    alias_suffix,
    forwards_to,
    note,
    is_favorite
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, vault_id, user_id, title, alias_prefix, alias_suffix, forwards_to, note, is_favorite, created_at, updated_at, last_used_at
`

type CreateAliasItemParams struct {
	VaultID     int32       `json:"vault_id"`
	UserID      int32       `json:"user_id"`
	Title       string      `json:"title"`
	AliasPrefix string      `json:"alias_prefix"`
	AliasSuffix string      `json:"alias_suffix"`
	ForwardsTo  string      `json:"forwards_to"`
	Note        pgtype.Text `json:"note"`
	IsFavorite  bool        `json:"is_favorite"`
}

func (q *Queries) CreateAliasItem(ctx context.Context, arg CreateAliasItemParams) (VaultAliasItem, error) {
	row := q.db.QueryRow(ctx, createAliasItem,
		arg.VaultID,
		arg.UserID,
		arg.Title,
		arg.AliasPrefix,
		arg.AliasSuffix,
		arg.ForwardsTo,
		arg.Note,
		arg.IsFavorite,
	)
	var i VaultAliasItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.AliasPrefix,
		&i.AliasSuffix,
		&i.ForwardsTo,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAliasAttachment = `-- name: DeleteAliasAttachment :exec
DELETE FROM vault_alias_attachments
WHERE id = $1 AND alias_item_id = $2
`

type DeleteAliasAttachmentParams struct {
	ID          int32 `json:"id"`
	AliasItemID int32 `json:"alias_item_id"`
}

func (q *Queries) DeleteAliasAttachment(ctx context.Context, arg DeleteAliasAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteAliasAttachment, arg.ID, arg.AliasItemID)
	return err
}

const deleteAliasItem = `-- name: DeleteAliasItem :exec
DELETE FROM vault_alias_items
WHERE id = $1 AND user_id = $2
`

type DeleteAliasItemParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteAliasItem(ctx context.Context, arg DeleteAliasItemParams) error {
	_, err := q.db.Exec(ctx, deleteAliasItem, arg.ID, arg.UserID)
	return err
}

const deleteAllAliasAttachments = `-- name: DeleteAllAliasAttachments :exec
DELETE FROM vault_alias_attachments
WHERE alias_item_id = $1
`

func (q *Queries) DeleteAllAliasAttachments(ctx context.Context, aliasItemID int32) error {
	_, err := q.db.Exec(ctx, deleteAllAliasAttachments, aliasItemID)
	return err
}

const getAliasAttachmentByID = `-- name: GetAliasAttachmentByID :one
SELECT id, alias_item_id, filename, file_path, file_size, mime_type, created_at FROM vault_alias_attachments
WHERE id = $1 AND alias_item_id = $2
`

type GetAliasAttachmentByIDParams struct {
	ID          int32 `json:"id"`
	AliasItemID int32 `json:"alias_item_id"`
}

func (q *Queries) GetAliasAttachmentByID(ctx context.Context, arg GetAliasAttachmentByIDParams) (VaultAliasAttachment, error) {
	row := q.db.QueryRow(ctx, getAliasAttachmentByID, arg.ID, arg.AliasItemID)
	var i VaultAliasAttachment
	err := row.Scan(
		&i.ID,
		&i.AliasItemID,
		&i.Filename,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const getAliasAttachments = `-- name: GetAliasAttachments :many
SELECT id, alias_item_id, filename, file_path, file_size, mime_type, created_at FROM vault_alias_attachments
WHERE alias_item_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAliasAttachments(ctx context.Context, aliasItemID int32) ([]VaultAliasAttachment, error) {
	rows, err := q.db.Query(ctx, getAliasAttachments, aliasItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultAliasAttachment{}
	for rows.Next() {
		var i VaultAliasAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AliasItemID,
			&i.Filename,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAliasItemByID = `-- name: GetAliasItemByID :one
SELECT id, vault_id, user_id, title, alias_prefix, alias_suffix, forwards_to, note, is_favorite, created_at, updated_at, last_used_at FROM vault_alias_items
WHERE id = $1 AND user_id = $2
`

type GetAliasItemByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetAliasItemByID(ctx context.Context, arg GetAliasItemByIDParams) (VaultAliasItem, error) {
	row := q.db.QueryRow(ctx, getAliasItemByID, arg.ID, arg.UserID)
	var i VaultAliasItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.AliasPrefix,
		&i.AliasSuffix,
		&i.ForwardsTo,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserAliasItems = `-- name: GetUserAliasItems :many
SELECT id, vault_id, user_id, title, alias_prefix, alias_suffix, forwards_to, note, is_favorite, created_at, updated_at, last_used_at FROM vault_alias_items
WHERE user_id = $1
ORDER BY is_favorite DESC, updated_at DESC
`

func (q *Queries) GetUserAliasItems(ctx context.Context, userID int32) ([]VaultAliasItem, error) {
	rows, err := q.db.Query(ctx, getUserAliasItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultAliasItem{}
	for rows.Next() {
		var i VaultAliasItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Title,
			&i.AliasPrefix,
			&i.AliasSuffix,
			&i.ForwardsTo,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultAliasItems = `-- name: GetVaultAliasItems :many
SELECT id, vault_id, user_id, title, alias_prefix, alias_suffix, forwards_to, note, is_favorite, created_at, updated_at, last_used_at FROM vault_alias_items
WHERE vault_id = $1 AND user_id = $2
ORDER BY is_favorite DESC, updated_at DESC
`

type GetVaultAliasItemsParams struct {
	VaultID int32 `json:"vault_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) GetVaultAliasItems(ctx context.Context, arg GetVaultAliasItemsParams) ([]VaultAliasItem, error) {
	rows, err := q.db.Query(ctx, getVaultAliasItems, arg.VaultID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultAliasItem{}
	for rows.Next() {
		var i VaultAliasItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Title,
			&i.AliasPrefix,
			&i.AliasSuffix,
			&i.ForwardsTo,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAliasItems = `-- name: SearchAliasItems :many
SELECT id, vault_id, user_id, title, alias_prefix, alias_suffix, forwards_to, note, is_favorite, created_at, updated_at, last_used_at FROM vault_alias_items
WHERE user_id = $1 AND (
    title ILIKE '%' || $2 || '%' OR
    alias_prefix ILIKE '%' || $2 || '%' OR
    alias_suffix ILIKE '%' || $2 || '%' OR
    forwards_to ILIKE '%' || $2 || '%' OR
    note ILIKE '%' || $2 || '%'
)
ORDER BY is_favorite DESC, updated_at DESC
`

type SearchAliasItemsParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchAliasItems(ctx context.Context, arg SearchAliasItemsParams) ([]VaultAliasItem, error) {
	rows, err := q.db.Query(ctx, searchAliasItems, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultAliasItem{}
	for rows.Next() {
		var i VaultAliasItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Title,
			&i.AliasPrefix,
			&i.AliasSuffix,
			&i.ForwardsTo,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleAliasItemFavorite = `-- name: ToggleAliasItemFavorite :one
UPDATE vault_alias_items
SET 
    is_favorite = NOT is_favorite,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, vault_id, user_id, title, alias_prefix, alias_suffix, forwards_to, note, is_favorite, created_at, updated_at, last_used_at
`

type ToggleAliasItemFavoriteParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) ToggleAliasItemFavorite(ctx context.Context, arg ToggleAliasItemFavoriteParams) (VaultAliasItem, error) {
	row := q.db.QueryRow(ctx, toggleAliasItemFavorite, arg.ID, arg.UserID)
	var i VaultAliasItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.AliasPrefix,
		&i.AliasSuffix,
		&i.ForwardsTo,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateAliasItem = `-- name: UpdateAliasItem :one
UPDATE vault_alias_items
SET 
    title = $2,
    alias_prefix = $3,
    alias_suffix = $4,
    forwards_to = $5,
    note = $6,
    is_favorite = $7,
    updated_at = NOW()
WHERE id = $1 AND user_id = $8
RETURNING id, vault_id, user_id, title, alias_prefix, alias_suffix, forwards_to, note, is_favorite, created_at, updated_at, last_used_at
`

type UpdateAliasItemParams struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	AliasPrefix string      `json:"alias_prefix"`
	AliasSuffix string      `json:"alias_suffix"`
	ForwardsTo  string      `json:"forwards_to"`
	Note        pgtype.Text `json:"note"`
	IsFavorite  bool        `json:"is_favorite"`
	UserID      int32       `json:"user_id"`
}

func (q *Queries) UpdateAliasItem(ctx context.Context, arg UpdateAliasItemParams) (VaultAliasItem, error) {
	row := q.db.QueryRow(ctx, updateAliasItem,
		arg.ID,
		arg.Title,
		arg.AliasPrefix,
		arg.AliasSuffix,
		arg.ForwardsTo,
		arg.Note,
		arg.IsFavorite,
		arg.UserID,
	)
	var i VaultAliasItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Title,
		&i.AliasPrefix,
		&i.AliasSuffix,
		&i.ForwardsTo,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateAliasItemLastUsed = `-- name: UpdateAliasItemLastUsed :exec
UPDATE vault_alias_items
SET last_used_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateAliasItemLastUsedParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) UpdateAliasItemLastUsed(ctx context.Context, arg UpdateAliasItemLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateAliasItemLastUsed, arg.ID, arg.UserID)
	return err
}
