// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_versions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVaultVersions = `-- name: CountVaultVersions :one
SELECT COUNT(*) FROM vault_versions
WHERE vault_id = $1
`

func (q *Queries) CountVaultVersions(ctx context.Context, vaultID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countVaultVersions, vaultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVaultVersion = `-- name: CreateVaultVersion :one
INSERT INTO vault_versions (
    vault_id,
    object_key,
    mac,
    created_by_device
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, vault_id, object_key, mac, created_by_device, created_at
`

type CreateVaultVersionParams struct {
	VaultID         int32       `json:"vault_id"`
	ObjectKey       string      `json:"object_key"`
	Mac             []byte      `json:"mac"`
	CreatedByDevice pgtype.UUID `json:"created_by_device"`
}

func (q *Queries) CreateVaultVersion(ctx context.Context, arg CreateVaultVersionParams) (VaultVersion, error) {
	row := q.db.QueryRow(ctx, createVaultVersion,
		arg.VaultID,
		arg.ObjectKey,
		arg.Mac,
		arg.CreatedByDevice,
	)
	var i VaultVersion
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.ObjectKey,
		&i.Mac,
		&i.CreatedByDevice,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldVaultVersions = `-- name: DeleteOldVaultVersions :exec
DELETE FROM vault_versions v1
WHERE v1.vault_id = $1 
AND v1.id < (
    SELECT MAX(v2.id) - $2 
    FROM vault_versions v2
    WHERE v2.vault_id = $1
)
`

type DeleteOldVaultVersionsParams struct {
	VaultID int32 `json:"vault_id"`
	ID      int32 `json:"id"`
}

func (q *Queries) DeleteOldVaultVersions(ctx context.Context, arg DeleteOldVaultVersionsParams) error {
	_, err := q.db.Exec(ctx, deleteOldVaultVersions, arg.VaultID, arg.ID)
	return err
}

const getLatestVaultVersion = `-- name: GetLatestVaultVersion :one
SELECT id, vault_id, object_key, mac, created_by_device, created_at
FROM vault_versions
WHERE vault_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestVaultVersion(ctx context.Context, vaultID int32) (VaultVersion, error) {
	row := q.db.QueryRow(ctx, getLatestVaultVersion, vaultID)
	var i VaultVersion
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.ObjectKey,
		&i.Mac,
		&i.CreatedByDevice,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultVersionByID = `-- name: GetVaultVersionByID :one
SELECT id, vault_id, object_key, mac, created_by_device, created_at
FROM vault_versions
WHERE id = $1
`

func (q *Queries) GetVaultVersionByID(ctx context.Context, id int32) (VaultVersion, error) {
	row := q.db.QueryRow(ctx, getVaultVersionByID, id)
	var i VaultVersion
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.ObjectKey,
		&i.Mac,
		&i.CreatedByDevice,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultVersionByIDAndVault = `-- name: GetVaultVersionByIDAndVault :one
SELECT id, vault_id, object_key, mac, created_by_device, created_at
FROM vault_versions
WHERE vault_id = $1 AND id = $2
`

type GetVaultVersionByIDAndVaultParams struct {
	VaultID int32 `json:"vault_id"`
	ID      int32 `json:"id"`
}

func (q *Queries) GetVaultVersionByIDAndVault(ctx context.Context, arg GetVaultVersionByIDAndVaultParams) (VaultVersion, error) {
	row := q.db.QueryRow(ctx, getVaultVersionByIDAndVault, arg.VaultID, arg.ID)
	var i VaultVersion
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.ObjectKey,
		&i.Mac,
		&i.CreatedByDevice,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultVersionsByVaultID = `-- name: GetVaultVersionsByVaultID :many
SELECT id, vault_id, object_key, mac, created_by_device, created_at
FROM vault_versions
WHERE vault_id = $1
ORDER BY id DESC
LIMIT $2
`

type GetVaultVersionsByVaultIDParams struct {
	VaultID int32 `json:"vault_id"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) GetVaultVersionsByVaultID(ctx context.Context, arg GetVaultVersionsByVaultIDParams) ([]VaultVersion, error) {
	rows, err := q.db.Query(ctx, getVaultVersionsByVaultID, arg.VaultID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultVersion{}
	for rows.Next() {
		var i VaultVersion
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.ObjectKey,
			&i.Mac,
			&i.CreatedByDevice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultVersionsSinceID = `-- name: GetVaultVersionsSinceID :many
SELECT id, vault_id, object_key, mac, created_by_device, created_at
FROM vault_versions
WHERE vault_id = $1 AND id > $2
ORDER BY id ASC
`

type GetVaultVersionsSinceIDParams struct {
	VaultID int32 `json:"vault_id"`
	ID      int32 `json:"id"`
}

func (q *Queries) GetVaultVersionsSinceID(ctx context.Context, arg GetVaultVersionsSinceIDParams) ([]VaultVersion, error) {
	rows, err := q.db.Query(ctx, getVaultVersionsSinceID, arg.VaultID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultVersion{}
	for rows.Next() {
		var i VaultVersion
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.ObjectKey,
			&i.Mac,
			&i.CreatedByDevice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
