// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_keys.sql

package sqlc

import (
	"context"
)

const createVaultKey = `-- name: CreateVaultKey :one
INSERT INTO vault_keys (
    vault_id,
    wrapped_vek,
    wrap_iv,
    wrap_tag,
    kdf_salt,
    kdf_params,
    version,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, vault_id, wrapped_vek, wrap_iv, wrap_tag, kdf_salt, kdf_params, version, created_at, updated_at
`

type CreateVaultKeyParams struct {
	VaultID    int32  `json:"vault_id"`
	WrappedVek []byte `json:"wrapped_vek"`
	WrapIv     []byte `json:"wrap_iv"`
	WrapTag    []byte `json:"wrap_tag"`
	KdfSalt    []byte `json:"kdf_salt"`
	KdfParams  []byte `json:"kdf_params"`
	Version    int32  `json:"version"`
}

func (q *Queries) CreateVaultKey(ctx context.Context, arg CreateVaultKeyParams) (VaultKey, error) {
	row := q.db.QueryRow(ctx, createVaultKey,
		arg.VaultID,
		arg.WrappedVek,
		arg.WrapIv,
		arg.WrapTag,
		arg.KdfSalt,
		arg.KdfParams,
		arg.Version,
	)
	var i VaultKey
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.WrappedVek,
		&i.WrapIv,
		&i.WrapTag,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVaultKeys = `-- name: DeleteVaultKeys :exec
DELETE FROM vault_keys
WHERE vault_id = $1
`

func (q *Queries) DeleteVaultKeys(ctx context.Context, vaultID int32) error {
	_, err := q.db.Exec(ctx, deleteVaultKeys, vaultID)
	return err
}

const getAllVaultKeyVersions = `-- name: GetAllVaultKeyVersions :many
SELECT id, vault_id, wrapped_vek, wrap_iv, wrap_tag, kdf_salt, kdf_params, version, created_at, updated_at FROM vault_keys
WHERE vault_id = $1
ORDER BY version DESC
`

func (q *Queries) GetAllVaultKeyVersions(ctx context.Context, vaultID int32) ([]VaultKey, error) {
	rows, err := q.db.Query(ctx, getAllVaultKeyVersions, vaultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultKey{}
	for rows.Next() {
		var i VaultKey
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.WrappedVek,
			&i.WrapIv,
			&i.WrapTag,
			&i.KdfSalt,
			&i.KdfParams,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultKeyByVaultID = `-- name: GetVaultKeyByVaultID :one
SELECT id, vault_id, wrapped_vek, wrap_iv, wrap_tag, kdf_salt, kdf_params, version, created_at, updated_at FROM vault_keys
WHERE vault_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetVaultKeyByVaultID(ctx context.Context, vaultID int32) (VaultKey, error) {
	row := q.db.QueryRow(ctx, getVaultKeyByVaultID, vaultID)
	var i VaultKey
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.WrappedVek,
		&i.WrapIv,
		&i.WrapTag,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVaultKeyByVaultIDAndVersion = `-- name: GetVaultKeyByVaultIDAndVersion :one
SELECT id, vault_id, wrapped_vek, wrap_iv, wrap_tag, kdf_salt, kdf_params, version, created_at, updated_at FROM vault_keys
WHERE vault_id = $1 AND version = $2
LIMIT 1
`

type GetVaultKeyByVaultIDAndVersionParams struct {
	VaultID int32 `json:"vault_id"`
	Version int32 `json:"version"`
}

func (q *Queries) GetVaultKeyByVaultIDAndVersion(ctx context.Context, arg GetVaultKeyByVaultIDAndVersionParams) (VaultKey, error) {
	row := q.db.QueryRow(ctx, getVaultKeyByVaultIDAndVersion, arg.VaultID, arg.Version)
	var i VaultKey
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.WrappedVek,
		&i.WrapIv,
		&i.WrapTag,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVaultKey = `-- name: UpdateVaultKey :one
UPDATE vault_keys
SET 
    wrapped_vek = $2,
    wrap_iv = $3,
    wrap_tag = $4,
    kdf_salt = $5,
    kdf_params = $6,
    version = $7,
    updated_at = NOW()
WHERE vault_id = $1
RETURNING id, vault_id, wrapped_vek, wrap_iv, wrap_tag, kdf_salt, kdf_params, version, created_at, updated_at
`

type UpdateVaultKeyParams struct {
	VaultID    int32  `json:"vault_id"`
	WrappedVek []byte `json:"wrapped_vek"`
	WrapIv     []byte `json:"wrap_iv"`
	WrapTag    []byte `json:"wrap_tag"`
	KdfSalt    []byte `json:"kdf_salt"`
	KdfParams  []byte `json:"kdf_params"`
	Version    int32  `json:"version"`
}

func (q *Queries) UpdateVaultKey(ctx context.Context, arg UpdateVaultKeyParams) (VaultKey, error) {
	row := q.db.QueryRow(ctx, updateVaultKey,
		arg.VaultID,
		arg.WrappedVek,
		arg.WrapIv,
		arg.WrapTag,
		arg.KdfSalt,
		arg.KdfParams,
		arg.Version,
	)
	var i VaultKey
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.WrappedVek,
		&i.WrapIv,
		&i.WrapTag,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
