// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_card_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCardItem = `-- name: CreateCardItem :one
INSERT INTO vault_card_items (
    vault_id,
    user_id,
    name,
    card_number_encrypted,
    expiration_date,
    security_code_encrypted,
    pin_encrypted,
    note,
    is_favorite
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, vault_id, user_id, name, card_number_encrypted, expiration_date, security_code_encrypted, pin_encrypted, note, is_favorite, created_at, updated_at, last_used_at
`

type CreateCardItemParams struct {
	VaultID               int32       `json:"vault_id"`
	UserID                int32       `json:"user_id"`
	Name                  string      `json:"name"`
	CardNumberEncrypted   string      `json:"card_number_encrypted"`
	ExpirationDate        pgtype.Text `json:"expiration_date"`
	SecurityCodeEncrypted pgtype.Text `json:"security_code_encrypted"`
	PinEncrypted          pgtype.Text `json:"pin_encrypted"`
	Note                  pgtype.Text `json:"note"`
	IsFavorite            bool        `json:"is_favorite"`
}

func (q *Queries) CreateCardItem(ctx context.Context, arg CreateCardItemParams) (VaultCardItem, error) {
	row := q.db.QueryRow(ctx, createCardItem,
		arg.VaultID,
		arg.UserID,
		arg.Name,
		arg.CardNumberEncrypted,
		arg.ExpirationDate,
		arg.SecurityCodeEncrypted,
		arg.PinEncrypted,
		arg.Note,
		arg.IsFavorite,
	)
	var i VaultCardItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Name,
		&i.CardNumberEncrypted,
		&i.ExpirationDate,
		&i.SecurityCodeEncrypted,
		&i.PinEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteCardItem = `-- name: DeleteCardItem :exec
DELETE FROM vault_card_items
WHERE id = $1 AND user_id = $2
`

type DeleteCardItemParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteCardItem(ctx context.Context, arg DeleteCardItemParams) error {
	_, err := q.db.Exec(ctx, deleteCardItem, arg.ID, arg.UserID)
	return err
}

const getCardItemByID = `-- name: GetCardItemByID :one
SELECT id, vault_id, user_id, name, card_number_encrypted, expiration_date, security_code_encrypted, pin_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_card_items
WHERE id = $1 AND user_id = $2
`

type GetCardItemByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetCardItemByID(ctx context.Context, arg GetCardItemByIDParams) (VaultCardItem, error) {
	row := q.db.QueryRow(ctx, getCardItemByID, arg.ID, arg.UserID)
	var i VaultCardItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Name,
		&i.CardNumberEncrypted,
		&i.ExpirationDate,
		&i.SecurityCodeEncrypted,
		&i.PinEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserCardItems = `-- name: GetUserCardItems :many
SELECT id, vault_id, user_id, name, card_number_encrypted, expiration_date, security_code_encrypted, pin_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_card_items
WHERE user_id = $1
ORDER BY is_favorite DESC, updated_at DESC
`

func (q *Queries) GetUserCardItems(ctx context.Context, userID int32) ([]VaultCardItem, error) {
	rows, err := q.db.Query(ctx, getUserCardItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultCardItem{}
	for rows.Next() {
		var i VaultCardItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Name,
			&i.CardNumberEncrypted,
			&i.ExpirationDate,
			&i.SecurityCodeEncrypted,
			&i.PinEncrypted,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultCardItems = `-- name: GetVaultCardItems :many
SELECT id, vault_id, user_id, name, card_number_encrypted, expiration_date, security_code_encrypted, pin_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_card_items
WHERE vault_id = $1 AND user_id = $2
ORDER BY is_favorite DESC, updated_at DESC
`

type GetVaultCardItemsParams struct {
	VaultID int32 `json:"vault_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) GetVaultCardItems(ctx context.Context, arg GetVaultCardItemsParams) ([]VaultCardItem, error) {
	rows, err := q.db.Query(ctx, getVaultCardItems, arg.VaultID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultCardItem{}
	for rows.Next() {
		var i VaultCardItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Name,
			&i.CardNumberEncrypted,
			&i.ExpirationDate,
			&i.SecurityCodeEncrypted,
			&i.PinEncrypted,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCardItems = `-- name: SearchCardItems :many
SELECT id, vault_id, user_id, name, card_number_encrypted, expiration_date, security_code_encrypted, pin_encrypted, note, is_favorite, created_at, updated_at, last_used_at FROM vault_card_items
WHERE user_id = $1 AND (
    name ILIKE '%' || $2 || '%' OR
    note ILIKE '%' || $2 || '%'
)
ORDER BY is_favorite DESC, updated_at DESC
`

type SearchCardItemsParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchCardItems(ctx context.Context, arg SearchCardItemsParams) ([]VaultCardItem, error) {
	rows, err := q.db.Query(ctx, searchCardItems, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultCardItem{}
	for rows.Next() {
		var i VaultCardItem
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.UserID,
			&i.Name,
			&i.CardNumberEncrypted,
			&i.ExpirationDate,
			&i.SecurityCodeEncrypted,
			&i.PinEncrypted,
			&i.Note,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleCardItemFavorite = `-- name: ToggleCardItemFavorite :one
UPDATE vault_card_items
SET 
    is_favorite = NOT is_favorite,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, vault_id, user_id, name, card_number_encrypted, expiration_date, security_code_encrypted, pin_encrypted, note, is_favorite, created_at, updated_at, last_used_at
`

type ToggleCardItemFavoriteParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) ToggleCardItemFavorite(ctx context.Context, arg ToggleCardItemFavoriteParams) (VaultCardItem, error) {
	row := q.db.QueryRow(ctx, toggleCardItemFavorite, arg.ID, arg.UserID)
	var i VaultCardItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Name,
		&i.CardNumberEncrypted,
		&i.ExpirationDate,
		&i.SecurityCodeEncrypted,
		&i.PinEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateCardItem = `-- name: UpdateCardItem :one
UPDATE vault_card_items
SET 
    name = $2,
    card_number_encrypted = $3,
    expiration_date = $4,
    security_code_encrypted = $5,
    pin_encrypted = $6,
    note = $7,
    is_favorite = $8,
    updated_at = NOW()
WHERE id = $1 AND user_id = $9
RETURNING id, vault_id, user_id, name, card_number_encrypted, expiration_date, security_code_encrypted, pin_encrypted, note, is_favorite, created_at, updated_at, last_used_at
`

type UpdateCardItemParams struct {
	ID                    int32       `json:"id"`
	Name                  string      `json:"name"`
	CardNumberEncrypted   string      `json:"card_number_encrypted"`
	ExpirationDate        pgtype.Text `json:"expiration_date"`
	SecurityCodeEncrypted pgtype.Text `json:"security_code_encrypted"`
	PinEncrypted          pgtype.Text `json:"pin_encrypted"`
	Note                  pgtype.Text `json:"note"`
	IsFavorite            bool        `json:"is_favorite"`
	UserID                int32       `json:"user_id"`
}

func (q *Queries) UpdateCardItem(ctx context.Context, arg UpdateCardItemParams) (VaultCardItem, error) {
	row := q.db.QueryRow(ctx, updateCardItem,
		arg.ID,
		arg.Name,
		arg.CardNumberEncrypted,
		arg.ExpirationDate,
		arg.SecurityCodeEncrypted,
		arg.PinEncrypted,
		arg.Note,
		arg.IsFavorite,
		arg.UserID,
	)
	var i VaultCardItem
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.UserID,
		&i.Name,
		&i.CardNumberEncrypted,
		&i.ExpirationDate,
		&i.SecurityCodeEncrypted,
		&i.PinEncrypted,
		&i.Note,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateCardItemLastUsed = `-- name: UpdateCardItemLastUsed :exec
UPDATE vault_card_items
SET last_used_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateCardItemLastUsedParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) UpdateCardItemLastUsed(ctx context.Context, arg UpdateCardItemLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateCardItemLastUsed, arg.ID, arg.UserID)
	return err
}
