/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminInsightsRouteImport } from './routes/admin/insights'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminCustomizeRouteImport } from './routes/admin/customize'
import { Route as AdminChatbotRouteImport } from './routes/admin/chatbot'
import { Route as legalTermsRouteImport } from './routes/(legal)/terms'
import { Route as legalPrivacyRouteImport } from './routes/(legal)/privacy'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomizeRoute = AdminCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatbotRoute = AdminChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AdminRouteRoute,
} as any)
const legalTermsRoute = legalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalPrivacyRoute = legalPrivacyRouteImport.update({
  id: '/(legal)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/privacy': typeof legalPrivacyRoute
  '/terms': typeof legalTermsRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/privacy': typeof legalPrivacyRoute
  '/terms': typeof legalTermsRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(legal)/privacy': typeof legalPrivacyRoute
  '/(legal)/terms': typeof legalTermsRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/privacy'
    | '/terms'
    | '/admin/chatbot'
    | '/admin/customize'
    | '/admin/home'
    | '/admin/insights'
    | '/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/privacy'
    | '/terms'
    | '/admin/chatbot'
    | '/admin/customize'
    | '/admin/home'
    | '/admin/insights'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(legal)/privacy'
    | '/(legal)/terms'
    | '/admin/chatbot'
    | '/admin/customize'
    | '/admin/home'
    | '/admin/insights'
    | '/admin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  legalPrivacyRoute: typeof legalPrivacyRoute
  legalTermsRoute: typeof legalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customize': {
      id: '/admin/customize'
      path: '/customize'
      fullPath: '/admin/customize'
      preLoaderRoute: typeof AdminCustomizeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chatbot': {
      id: '/admin/chatbot'
      path: '/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminChatbotRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(legal)/terms': {
      id: '/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/privacy': {
      id: '/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminChatbotRoute: typeof AdminChatbotRoute
  AdminCustomizeRoute: typeof AdminCustomizeRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminChatbotRoute: AdminChatbotRoute,
  AdminCustomizeRoute: AdminCustomizeRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  legalPrivacyRoute: legalPrivacyRoute,
  legalTermsRoute: legalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
